ck-project/ck-project/Controllers/LeadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using Microsoft.AspNet.Identity;
using ck_project.Helpers;



namespace ck_project.Controllers
{
    [Authorize]

    public class LeadController : Controller
    {
        //Creating the DB connecton
        ckdatabase db = new ckdatabase();
        static List<lead> lst = new List<lead>();

        // GET: Lead




        public ActionResult ListLead(int? page, string search = null, string Type = null, string Start = null, string end = null, string msg = null)
        {

            int type = string.IsNullOrEmpty(Type) ? 3 : int.Parse(Type);
            DateTime start = string.IsNullOrEmpty(Start) ? DateTime.MinValue : DateTime.Parse(Start);
            DateTime end2 = string.IsNullOrEmpty(end) ? DateTime.MaxValue : DateTime.Parse(end);
            TimeSpan ts = new TimeSpan(23, 59, 59);
            end2 = end2.Date + ts;

            int statusNbr = 0;
            if (!string.IsNullOrEmpty(Type))
            {
                statusNbr = Int32.Parse(Type);
            }

            try
            {
                ViewBag.m = msg;
                var ClassInfo = new List<SelectListItem> {
                    new SelectListItem() { Text = "All", Selected = true, Value = "" }
                };
                ClassInfo.AddRange(db.project_status.Where(CCVV => CCVV.project_status_name != "closed").Select(b => new SelectListItem

                {
                    Text = b.project_status_name,
                    Selected = false,
                    Value = b.project_status_number.ToString()
                }));
                ViewBag.lead_type = ClassInfo;
                var result = db.leads.Where(l => (l.project_status_number != 6 && l.deleted == false)
                                      && l.lead_date >= start && l.lead_date <= end2
                                      && (string.IsNullOrEmpty(Type) || l.project_status_number == statusNbr)
                                      && (string.IsNullOrEmpty(search) || l.project_name.Contains(search))).ToList();


                LeadController.lst = result;
                return View(result.ToPagedList(page ?? 1, 8));

                //return View(db.leads.Where(x => (x.project_name.Contains(search) || search == null) && x.project_status_number == type && (x.project_status_number != 6 && x.deleted == false)).ToList());
            }
            catch (Exception e)
            {
                ViewBag.m = "Something went wrong ... " + e.Message;
                return View();
            }
        }


        public ActionResult Add(int id, String msg = null, string add = null)
        {
            ViewBag.add = add;
            ViewBag.m = msg;
            try
            {
                List<SelectListItem> CustomerInfo = new List<SelectListItem>();
                CustomerInfo.AddRange(db.customers.Where(x => x.deleted != true).Select(a => new SelectListItem
                {
                    Text = a.customer_lastname,
                    Selected = false,
                    Value = a.customer_number.ToString()
                }));

                var ClassInfo = new List<SelectListItem>();
                ClassInfo.AddRange(db.project_class.Where(x => x.deleted != true).Select(b => new SelectListItem
                {
                    Text = b.class_name,
                    Selected = false,
                    Value = b.class_number.ToString()
                }));

                var StatusInfo = new List<SelectListItem>();
                StatusInfo.AddRange(db.project_status.Where(x => x.deleted != true).Select(c => new SelectListItem
                {
                    Text = c.project_status_name,
                    Selected = false,
                    Value = c.project_status_number.ToString()
                }));

                var ProjectTypeInfo = new List<SelectListItem>();
                ProjectTypeInfo.AddRange(db.project_type.Where(x => x.deleted != true).Select(b => new SelectListItem
                {
                    Text = b.project_type_name,
                    Selected = false,
                    Value = b.project_type_number.ToString()
                }));

                var SourceInfo = new List<SelectListItem>();
                SourceInfo.AddRange(db.lead_source.Where(x => x.deleted != true).Select(b => new SelectListItem
                {
                    Text = b.source_name,
                    Selected = false,
                    Value = b.source_number.ToString()
                }));

                var AddressInfo = new List<SelectListItem>();
                AddressInfo.AddRange(db.addresses.Where(x => x.deleted != true).Select(a => new SelectListItem
                {
                    Text = a.address_type,
                    Selected = false,
                    Value = a.address_number.ToString()
                }));

                //    var AddressCityInfo = new List<SelectListItem>();

                var EmpInfo = new List<SelectListItem>();
                EmpInfo.AddRange(db.employees.Where(x => x.deleted != true).Select(a => new SelectListItem
                {
                    Text = a.emp_firstname + " " + a.emp_lastname,
                    Selected = false,
                    Value = a.emp_number.ToString()
                }));

                var BranchInfo = new List<SelectListItem>();
                BranchInfo.AddRange(db.branches.Where(x => x.deleted != true).Select(a => new SelectListItem
                {
                    Text = a.branch_name,
                    Selected = false,
                    Value = a.branch_number.ToString()
                }));

                var DeliveryStatusInfo = new List<SelectListItem>();
                DeliveryStatusInfo.AddRange(db.delivery_status.Select(a => new SelectListItem
                {
                    Text = a.delivery_status_name,
                    Selected = false,
                    Value = a.delivery_status_number.ToString()
                }));

                var TaxExemptInfo = new List<SelectListItem> {


                  new SelectListItem() { Text = "Taxable", Value = "0" },
                new SelectListItem { Text = "Tax Exempt", Value = "1" }
            };

                ViewBag.TaxExemptInfo = TaxExemptInfo;
                //setting variable passing
                ViewBag.Customer_Info = CustomerInfo;
                ViewBag.Class_Info = ClassInfo;
                ViewBag.Status_Info = StatusInfo;
                ViewBag.ProjectType_Info = ProjectTypeInfo;
                ViewBag.Source_Info = SourceInfo;
                ViewBag.Address_Info = AddressInfo;
                ViewBag.Emp_Info = EmpInfo;
                ViewBag.Branch_Info = BranchInfo;
                ViewBag.DeliveryStatus_Info = DeliveryStatusInfo;

                var Sstate = new List<SelectListItem> {
               new SelectListItem() {Text="Alabama", Value="AL"},
        new SelectListItem() { Text="Alaska", Value="AK"},
        new SelectListItem() { Text="Arizona", Value="AZ"},
        new SelectListItem() { Text="Arkansas", Value="AR"},
        new SelectListItem() { Text="California", Value="CA"},
        new SelectListItem() { Text="Colorado", Value="CO"},
        new SelectListItem() { Text="Connecticut", Value="CT"},
        new SelectListItem() { Text="District of Columbia", Value="DC"},
        new SelectListItem() { Text="Delaware", Value="DE"},
        new SelectListItem() { Text="Florida", Value="FL"},
        new SelectListItem() { Text="Georgia", Value="GA"},
        new SelectListItem() { Text="Hawaii", Value="HI"},
        new SelectListItem() { Text="Idaho", Value="ID"},
        new SelectListItem() { Text="Illinois", Value="IL"},
        new SelectListItem() { Text="Indiana", Value="IN"},
        new SelectListItem() { Text="Iowa", Value="IA"},
        new SelectListItem() { Text="Kansas", Value="KS"},
        new SelectListItem() { Text="Kentucky", Value="KY"},
        new SelectListItem() { Text="Louisiana", Value="LA"},
        new SelectListItem() { Text="Maine", Value="ME"},
        new SelectListItem() { Text="Maryland", Value="MD"},
        new SelectListItem() { Text="Massachusetts", Value="MA"},
        new SelectListItem() { Text="Michigan", Value="MI"},
        new SelectListItem() { Text="Minnesota", Value="MN"},
        new SelectListItem() { Text="Mississippi", Value="MS"},
        new SelectListItem() { Text="Missouri", Value="MO"},
        new SelectListItem() { Text="Montana", Value="MT"},
        new SelectListItem() { Text="Nebraska", Value="NE"},
        new SelectListItem() { Text="Nevada", Value="NV"},
        new SelectListItem() { Text="New Hampshire", Value="NH"},
        new SelectListItem() { Text="New Jersey", Value="NJ"},
        new SelectListItem() { Text="New Mexico", Value="NM"},
        new SelectListItem() { Text="New York", Value="NY"},
        new SelectListItem() { Text="North Carolina", Value="NC"},
        new SelectListItem() { Text="North Dakota", Value="ND"},
        new SelectListItem() { Text="Ohio", Value="OH"},
        new SelectListItem() { Text="Oklahoma", Value="OK"},
        new SelectListItem() { Text="Oregon", Value="OR"},
        new SelectListItem() { Text="Pennsylvania", Value="PA"},
        new SelectListItem() { Text="Rhode Island", Value="RI"},
        new SelectListItem() { Text="South Carolina", Value="SC"},
        new SelectListItem() { Text="South Dakota", Value="SD"},
        new SelectListItem() { Text="Tennessee", Value="TN"},
        new SelectListItem() { Text="Texas", Value="TX"},
        new SelectListItem() { Text="Utah", Value="UT"},
        new SelectListItem() { Text="Vermont", Value="VT"},
        new SelectListItem() { Text="Virginia", Value="VA"},
        new SelectListItem() { Text="Washington", Value="WA"},

ck-project/ck-project/Controllers/PrintController.cs
using ck_project.Helpers;
using ck_project.Models;
using SelectPdf;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ck_project.Controllers
{
    [Authorize]
    public class PrintController : Controller
    {
        ckdatabase db = new ckdatabase();
        ProjSummaryHelper projSummaryHelper = new ProjSummaryHelper();
        
        public ActionResult Convert(string documentName, int id, string str)
        {
            // get the data
            var projSummary = new ProjectSummary
            {
                Branch = db.branches.ToList(),
            };
            var lead = db.leads.Where(l => l.lead_number == id).FirstOrDefault();

            if (lead != null)
            {
                projSummary.Lead = lead;
                projSummary = projSummaryHelper.SetCustomerData(lead, projSummary);
                projSummary = projSummaryHelper.SetAddresses(lead, projSummary);
                projSummary = projSummaryHelper.GetProductCategoryList(lead, projSummary);
                projSummary = projSummaryHelper.GetProductTotalMap(lead, projSummary);
                projSummary = projSummaryHelper.CalculateProposalAmtDue(id, projSummary);
                projSummary = projSummaryHelper.CalculateInstallCategoryCostMap(lead, projSummary);
                projSummary = projSummaryHelper.CalculateInstallationsData(lead, projSummary);
            }

            // instantiate a html to pdf converter object
            HtmlToPdf converter = new HtmlToPdf();

            // get html code from url
            string htmlString = this.RenderView(str, projSummary);

            // get base url (to resolve relative links to external resources)
            //this doesn't work with 'http' unless using the paid version
            //var uri = new Uri(url);
            //string baseUrl = uri.GetLeftPart(System.UriPartial.Authority);

            // set converter options
            converter.Options.PdfPageSize = PdfPageSize.Letter;
            converter.Options.PdfPageOrientation = PdfPageOrientation.Portrait;
            converter.Options.MarginLeft = 5;
            converter.Options.MarginRight = 5;
            converter.Options.MarginTop = 5;
            converter.Options.MarginBottom = 5;

            // create a new pdf document converting the html string
            PdfDocument doc = converter.ConvertHtmlString(htmlString);

            // get conversion result (contains document info from the web page)
            HtmlToPdfResult result = converter.ConversionResult;

            // set the document properties
            doc.DocumentInformation.Title = result.WebPageInformation.Title;
            doc.DocumentInformation.Subject = result.WebPageInformation.Description;
            doc.DocumentInformation.Keywords = result.WebPageInformation.Keywords;

            doc.DocumentInformation.Author = "CreativeKitchens";
            doc.DocumentInformation.CreationDate = DateTime.Now;

            // save pdf document
            byte[] pdf = doc.Save();

            // close pdf document
            doc.Close();

            //return resulted pdf document
            FileResult fileResult = new FileContentResult(pdf, "application/pdf")
            {
                FileDownloadName = documentName + ".pdf"
            };
            return fileResult;
        }
    }
}

ck-project/ck-project/Views/Home/DisplayProjects.cshtml
@model IEnumerable<ck_project.lead>

@{
    ViewBag.Title = "DisplayProjects";
}

<h2>DisplayProjects</h2>

<table class="table table-striped">
    <thead class="mdb-color darken-3">
        <tr>
            <th>Type</th>
            <th>Customer</th>
            <th>Title</th>
            <th>Status</th>
            <th>Last Modified</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.project_type.project_type_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.customer.customer_firstname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.project_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.project_status.project_status_name)
                </td>
                    @Html.DisplayFor(modelItem => item.last_status_date)
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.lead_number }) |
                    @Html.ActionLink("View", "View", new { id = item.lead_number }) |
                </td>
            </tr>
        }
    </tbody>

</table>

ck-project/ck-project/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">Login from "@User.Identity.Name" and the uid is "@ViewBag.uid", he is a "@ViewBag.role" Account.</p> 
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ck-project/ck-project/Views/Home/MainPage.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<ck_project.lead>

@{
    ViewBag.Title = "MainPage";
}

@Html.Partial("_MainMenu")

<div class="container">
    <table>
        <tr>
            <td style="width:720px"><h2>Projects</h2></td>
            <td style="width:700px" align="right"></td>
        </tr>
        <tr>
            <td>This page displays the curent user's leads.</td>
            <td rowspan="2">
                @using (Html.BeginForm("MainPage", "Home", FormMethod.Get))
                {
                    <b>Project Name: </b>
                    @Html.TextBox("name", ViewData.TemplateInfo.FormattedModelValue, new { placeholder = "Type project name here", @class = "search_box" });
                    <b>&nbsp;&nbsp;&nbsp;&nbsp;Status:</b>
                    @Html.DropDownList("status", (IEnumerable<SelectListItem>)ViewBag.projStatusList, new { @class="search_box" });
                    <div style="float:left; padding-top:12px"><b>&nbsp;&nbsp;&nbsp;Create Date:&nbsp;</b></div>
                    <div style="float:left; padding-right:10px; padding-top:4px"><input style="width:160px;" type="date" name="start" class="search_box" /></div>
                    <div style="float:left; padding-right:20px; padding-top:4px"><input style="width:160px" type="date" name="end" class="search_box" /></div>
                    <div style="padding-top:6px"><input type="submit" value="Search" class="btn btn-default" /></div>
                }
            </td>
        </tr>
        <tr>
            <td>
                <input type="button" value="Create Lead" onclick="location.href='@Url.Action("ListCustomers", "Customers")'" class="btn btn-default" style="width: 100px;" />
            </td>
        </tr>
    </table>
    <div style="padding-top:15px"></div>
    <table class="table table-striped" style="clear:both">
        <thead class="mdb-color darken-3">
            <tr>
                <th>@Html.ActionLink("Project Name","Sort",new { by="pn"})</th>
                <th>@Html.ActionLink("Customer", "Sort", new { by = "cu" })</th>
                <th>@Html.ActionLink("Project Type", "Sort", new { by= "pt" })</th>
                <th>@Html.ActionLink("Project Status", "Sort", new { by = "ps" })</th>
                <th>@Html.ActionLink("SalesPerson", "Sort", new { by = "sp" })</th>
                <th>@Html.ActionLink("Create Date", "Sort", new { by = "cd" })</th>
                <th>@Html.ActionLink("Last Update Date", "Sort", new { by = "lu" })</th>
            </tr>
        </thead>
        <tbody>
            @{
                if (Model != null)
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.project_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.customer.customer_firstname)
                                @Html.DisplayFor(modelItem => item.customer.customer_lastname)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.project_type.project_type_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.project_status.project_status_name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.lead_creator)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.lead_date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Last_update_date)
                            </td>
                            <td>
                                @Html.ActionLink("View", "ProjSummary", new { id = item.lead_number }) |
                                @Html.ActionLink("Edit", "Edit", "Lead", new { id = item.lead_number }, null) |
                                @Html.ActionLink("Delete", "Delete", "Lead", new { id = item.lead_number }, new { onclick = "return confirm('Are you sure you wish to delete the lead?');" })
                            </td>
                        </tr>
                    }
                }
            }
        </tbody>
    </table>
    @Html.PagedListPager(Model, page => Url.Action("MainPage", new { page, search = Request.QueryString["name"], Type = Request.QueryString["status"], Start = Request.QueryString["start"], end = Request.QueryString["end"] }), new PagedListRenderOptions() { DisplayPageCountAndCurrentLocation = true })
</div>

ck-project/ck-project/Views/Home/ProjPrint.cshtml
@{
    <link href="~/Content/Tabs.css" rel="stylesheet" type="text/css" />
    if (HttpContext.Current.User.IsInRole("Administrator"))
    {
        @Html.Partial("_AdminMenu")
    }
    else
    {
        @Html.Partial("_MainMenu")
    }
}

<style>
    .column {
        padding-top: 1%;
    }
</style>

<div class="container">
    <table>
        @{
            if (ViewBag.lead != null && ViewBag.lead.project_status.project_status_name.Equals("Closed"))
            {
                <tr>
                    <td colspan"5" style="width:1150px"><h2>Print Portal</h2></td>
                    <td style="width:50px">
                        <input type="button" value="Summary" onclick="location.href='@Url.Action("ProjSummary", "Home", new { id = ViewBag.leadNumber })'" class="btn btn-default" id="tabBtn" />
                    </td>
                </tr>
            }
            else
            {
                <tr>
                    <td style="width:947px"><h2>Print Portal</h2></td>
                    <td style="width:50px">
                        <input type="button" value="Customer" onclick="location.href='@Url.Action("Edit", "Customers", new { id = @ViewBag.lead.customer_number })'" class="btn btn-default" id="tabBtn" />
                    </td>
                    <td style="width:50px">
                        <input type="button" value="Lead" onclick="location.href='@Url.Action("Edit", "Lead", new { id = ViewBag.leadNumber })'" class="btn btn-default" id="tabBtn" />
                    </td>
                    <td style="width:50px">
                        <input type="button" value="Products" onclick="location.href='@Url.Action("View", "Product", new { id = ViewBag.leadNumber })'" class="btn btn-default" id="tabBtn" />
                    </td>
                    <td style="width:100px">
                        <input type="button" value="Installation" onclick="location.href='@Url.Action("Lis", "Install", new { lid = ViewBag.leadNumber })'" class="btn btn-default" id="tabBtn" />
                    </td>
                    <td style="width:50px">
                        <input type="button" value="Summary" onclick="location.href='@Url.Action("ProjSummary", "Home", new { id = ViewBag.leadNumber })'" class="btn btn-default" id="tabBtn" />
                    </td>
                </tr>
            }
        }
    </table>
    <hr />

    <div class="row top-buffer">
        <label class="col-md-4 text-center">FOR CUSTOMER</label>
        <label class="col-md-4 text-center">FOR INSTALLER</label>
        <label class="col-md-4 text-center">FOR INTERNAL</label>
        <div class="col-md-4 column" align="center">
            <input type="button" value="Proposal" onclick="location.href='@Url.Action("Convert", "Print", new { documentName = "Proposal", id = ViewBag.leadNumber, str = "Proposal" })'" class="btn btn-default" id="printBtn" />
        </div>
        <div class="col-md-4 column" align="center">
            <input type="button" value="Installation Details" onclick="location.href='@Url.Action("Convert", "Print", new { documentName = "Installation Details (Installers)", id = ViewBag.leadNumber, str = "InstallationDetailsForInstallers" })'" class="btn btn-default" id="printBtn" />
        </div>
        <div class="col-md-4 column" align="center">
            <input type="button" value="Lead Entry" onclick="location.href='@Url.Action("Convert", "Print", new { documentName = "Lead Entry", id = ViewBag.leadNumber, str = "LeadEntry" })'" class="btn btn-default" id="printBtn" />
        </div>
        <div class="col-md-4 column" align="center">
            <input type="button" value="Products (Exhibit A)" onclick="location.href='@Url.Action("Convert", "Print", new { documentName = "Products (Exhibit A)", id = ViewBag.leadNumber, str = "ProductsExternal" })'" class="btn btn-default" id="printBtn" />
        </div>
        <div class="col-md-4 col-md-offset-4 column" align="center">
            <input type="button" value="Products Ordering" onclick="location.href='@Url.Action("Convert", "Print", new { documentName = "Products Ordering", id = ViewBag.leadNumber, str = "ProductsInternal" })'" class="btn btn-default" id="printBtn" />
        </div>
        <div class="col-md-4 column" align="center">
            <input type="button" value="Scope of Work (Exhibit B)" onclick="location.href='@Url.Action("Convert", "Print", new { documentName = "Scope of Work (Exhibit B)", id = ViewBag.leadNumber, str = "ScopeOfWork" })'" class="btn btn-default" id="printBtn" />
        </div>
        <div class="col-md-4 col-md-offset-4 column" align="center">
            <input type="button" value="Installation Details" onclick="location.href='@Url.Action("Convert", "Print", new { documentName = "Installation Details (Internal)", id = ViewBag.leadNumber, str = "InstallationDetailsInternal" })'" class="btn btn-default" id="printBtn" />
        </div>
        <div class="col-md-4 column" align="center">
            <input type="button" value="Owner Product Agreement" onclick="location.href='@Url.Action("Convert", "Print", new { documentName = "Owner Product Agreement", id = ViewBag.leadNumber, str = "OwnerProductAgreement" })'" class="btn btn-default" id="printBtn" />
        </div>
        <div class="col-md-4 col-md-offset-4 column" align="center">
            <input type="button" value="Sold Job Notice" onclick="location.href='@Url.Action("Convert", "Print", new { documentName = "Sold Job Notice", id = ViewBag.leadNumber, str = "SoldJobNotice" })'" class="btn btn-default" id="printBtn" />
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(document).ready(function () {
            $(".navbar-nav li").removeClass("active");//this will remove the active class from
            //previously active menu item
            $('#lead').addClass('active');
        });
    </script>
}

ck-project/ck-project/Views/Home/ProjSummary_CustomerDetails.cshtml
@model ck_project.Models.ProjectSummary

<hr style="border:1px solid; border-color: darkgray" />
<table>
    <tr>
        <td></td>
        <td class="le_title">Customer:</td>
        <td class="le_data">
            @{
                if (Model.Customer != null)
                {
                    @Model.Customer.customer_firstname@:&nbsp;@Model.Customer.customer_lastname
                    }
            }
        </td>
        <td class="le_title">Primary Phone:</td>
        <td class="le_data">
            @{
                if (Model.Customer != null && Model.Customer.phone_number != null && !Model.Customer.phone_number.Equals(""))
                {
                    @String.Format("{0:(###) ###-####}", Convert.ToInt64(Model.Customer.phone_number))
                }
            }
        </td>
    </tr>
    <tr>
        <td></td>
        <td class="le_title">Address:</td>
        <td class="le_data">
            @{
                if (Model.Customer != null)
                {
                    @Model.Customer.address.address1
                }
            }
        </td>
        <td class="le_title">Alternate Phone:</td>
        <td class="le_data">
            @{
                if (Model.Customer != null && Model.Customer.second_phone_number != null && !Model.Customer.second_phone_number.Equals(""))
                {
                    @String.Format("{0:(###) ###-####}", Convert.ToInt64(Model.Customer.second_phone_number))
                }
            }
        </td>
    </tr>
    <tr>
        <td></td>
        <td class="le_title"></td>
        <td class="le_data">
            @{
                if (Model.Customer != null)
                {
                    @Model.Customer.address.city@:&#44;&nbsp;@Model.Customer.address.state&nbsp;@Model.Customer.address.zipcode
                    }
            }
        </td>
        <td class="le_title">Primary Email:</td>
        <td class="le_data">
            @{
                if (Model.Customer != null)
                {
                    @Model.Customer.email
                }
            }
        </td>
    </tr>
    <tr>
        <td colspan="3"></td>
        <td class="le_title">Secondary Email:</td>
        <td class="le_data">
            @{
                if (Model.Customer != null)
                {

                }
            }
        </td>
    </tr>
</table>