ck-project/ck-project/Controllers/InstallController.cs
using ck_project.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ck_project.Controllers
{
    [Authorize]
    public class InstallController : Controller
    { // GET: Install
        ckdatabase db = new ckdatabase();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Lis(int lid,string msg=null)
        {

            ViewBag.msg = msg;
            installation target = db.installations.Where(a => a.lead_number == lid).FirstOrDefault();
            ViewBag.mainc = new List<SelectListItem>
            {
               new SelectListItem{ Text="Kitchen",Value="kitchen"},
               new SelectListItem{ Text="Framing",Value="Framing"},
               new SelectListItem{ Text="Doors&Windows",Value="Doors_Windows"},
               new SelectListItem{ Text="Mechanicals",Value="MECHANICALS"},
               new SelectListItem{ Text="Electrical",Value="Electrical"},
               new SelectListItem{ Text="Finish",Value="Finish"},
               new SelectListItem{ Text="Cabinetry",Value="Cabinetry"},
               new SelectListItem{ Text="Countertops",Value="Countertops"},
               new SelectListItem{ Text="Appliance/Fixture Install",Value="Appliance"},
               new SelectListItem{ Text="GENERAL",Value="GENERAL"},
               new SelectListItem{ Text="BATH",Value="BATH"},
               new SelectListItem{ Text="MISC",Value="MISC"}
            };

            

            ViewBag.kitchen = new List<SelectListItem>
            {
                new SelectListItem{ Text="Appliance & Sink Demo",Value="asd"},
                 new SelectListItem{ Text="Cabinet & Top Demo",Value="ctd"},
                  new SelectListItem{ Text="Millwork Demo",Value="md"},
                   new SelectListItem{ Text="Floor - Ceiling - Wall Covering Demo",Value="fcwcd"},
                    new SelectListItem{ Text="Plumbing Demo",Value="pd"},
                     new SelectListItem{ Text="Electrical Demo",Value="ed"},
                      new SelectListItem{ Text="HVAC Demo",Value="hd"},
                       new SelectListItem{ Text="Windows & Door Demo",Value="wdd"},
                        new SelectListItem{ Text="Wood Framing Demo",Value="wfd"},
                         new SelectListItem{ Text="Misc Demo",Value="mid"}
            };

            ViewBag.framing = new List<SelectListItem> {
                new SelectListItem{ Text="Wall Framing",Value="WF"},
                new SelectListItem{ Text="Ceiling Framing",Value="CF"},
                new SelectListItem{ Text="Floor Framing",Value="FF"},
                new SelectListItem{ Text="Insulation",Value="ins"}
            };

            ViewBag.doorswindows = new List<SelectListItem> {
                new SelectListItem{Text="Doors",Value="Doors" },
                new SelectListItem{Text="Windows",Value="Windows" }
            };

            ViewBag.mech = new List<SelectListItem> {
                new SelectListItem{Text="Plumbing (Rough-In)",Value="Plumbing" },
                new SelectListItem{Text="HVAC",Value="hvac" }
            };

            ViewBag.elect = new List<SelectListItem> {
                new SelectListItem{Text="Wiring/Devices",Value="WD" },
                new SelectListItem{Text="Lighting",Value="lighting" }
            };

            ViewBag.finish = new List<SelectListItem> {
                new SelectListItem{Text="Ceiling and Walls",Value="caw" },
                new SelectListItem{Text="Flooring",Value="flooring" },
                new SelectListItem{Text="Millwork",Value="millwork" }
            };

            ViewBag.cabin = new List<SelectListItem> {
                new SelectListItem{Text="Cabinetry & Trim",Value="ct" }
            };

            ViewBag.counter = new List<SelectListItem> {
                new SelectListItem{Text="Countertop Installation",Value="CI" }
            };

            ViewBag.appliance = new List<SelectListItem> {
                new SelectListItem{ Text="Appliances And Fixtures Installation",Value="app"}
            };
            //372
            ViewBag.tbd = new List<SelectListItem> {
                new SelectListItem{ Text="Granite & Solid Surface Tops",Value="gsst"},
                new SelectListItem{Text="General",Value="General" }
            };

            ViewBag.bath = new List<SelectListItem> {
                new SelectListItem{ Text="Demo",Value="demo"},
                new SelectListItem{ Text="Wiring/Devices",Value="wd"},
                new SelectListItem{ Text="Walls/Finishes",Value="wf"},
                new SelectListItem{ Text="Flooring",Value="flooring"},
                new SelectListItem{ Text="Plumbing",Value="plumbing"},
                new SelectListItem{Text="Cabinetry & Trim",Value="ct" },
                new SelectListItem{Text="Countertop Installation",Value="CI" },
                new SelectListItem{Text="Lighting & Fixtures",Value="lighting" },
                new SelectListItem{Text="Millwork",Value="Millwork" }
            };

            ViewBag.misc = new List<SelectListItem> {
                new SelectListItem{ Text="Disclaimers",Value="disclaimers"}
            };
            List<employee> emplist = db.employees.Where(x => x.deleted == false).ToList();
            List<SelectListItem> al = new List<SelectListItem>();
                foreach (employee e in emplist) {
                al.Add(new SelectListItem { Text = e.emp_firstname + " " + e.emp_lastname, Value = e.emp_firstname });
            }
            ViewBag.emplist = al;


            //no installation yet
            //if ( target==null) {

            //    target = init(lid);

            //}
            var lead = db.leads.Where(l => l.lead_number == lid).First();
            ViewBag.lid = lid;
            ViewBag.customerNbr = lead.customer_number;

            return View(target);


        }

        public ActionResult custT(int iid)
        {
            List<tasks_installation> result = db.tasks_installation.Where(s => s.installation_number == iid & s.task_number > 408).ToList();
            return View(result);

        }

        [HttpPost]
        public ActionResult cusT(FormCollection fo)
        {
            int lid = int.Parse(fo["lid"]);


            return RedirectToAction("lis", new { lid = lid });
        }

        public ActionResult AddJob(string maincat,string subcat,int insnum=0,int mode=0) {
            
            List<task> option = db.tasks.Where(x => x.special_task == false && x.task_main_cat == maincat && x.task_sub_cat == subcat).ToList();
            List<SelectListItem> taskname = new List<SelectListItem>();
            foreach (task a in option) {
                taskname.Add(new SelectListItem { Text = a.task_name, Value =a.task_number.ToString() });
            }
            ViewBag.taskname = taskname;
            ViewBag.insnum = insnum;
            ViewBag.mode = mode;
           


            return PartialView();

        }
        //new task handler
        [HttpPost]
        public ActionResult handler(FormCollection fo) {
            int iid = int.Parse(fo["installation_number"]);
            string  msg = "The task was created successfully at " + System.DateTime.Now; ;
            int lid = db.installations.Where(a => a.installation_number == iid).First().lead_number;
            lead idk = db.leads.Where(d => d.lead_number == lid).First();
            GeneralHelper helper = new GeneralHelper();
            tasks_installation target = new tasks_installation();
            if (int.Parse(fo["mode"]) == 0)
            {
                target.hours = double.Parse(fo["hours"]);
                target.task_number = int.Parse(fo["task_number"]);
                target.m_cost = double.Parse(fo["m_cost"]);
                target.labor_cost= helper.GetInstallationLaborRate(idk)* target.hours;
                target.material_retail_cost = helper.GetInstallationMaterialRate(idk) * target.m_cost;
                target.installation_number = iid;
                try
                {
                    db.tasks_installation.Add(target);
                    db.SaveChanges(lid);
                    //db.SaveChanges(lid, "create new");

                }
                catch (Exception e)
                {
                    msg = e.Message;
                }
            }
            else {
                
                    task ctask = new task();
                    ctask.special_task = true;
                    ctask.task_main_cat = "MISC";
                    ctask.task_sub_cat = "Disclaimers";
                    ctask.task_name = fo["task_name"];
                    db.tasks.Add(ctask);
                    

                    target.task = ctask;

                    target.hours = double.Parse(fo["hours"]);
                    target.m_cost = double.Parse(fo["m_cost"]);
                target.labor_cost = helper.GetInstallationLaborRate(idk) * target.hours;
                target.material_retail_cost = helper.GetInstallationMaterialRate(idk) * target.m_cost;
                db.tasks_installation.Add(target);
                    target.installation_number = iid;
                    try
                    {
                        db.SaveChanges(lid);
                }
                catch (Exception e)
                {
                    msg = e.Message;

                }
            }


            return RedirectToAction("lis", new { lid = lid,msg=msg });
        }

        public ActionResult readtask(int lid,string maincat,string subcat) {
            installation t = db.installations.Where(r => r.lead_number == lid).First();
            int tt = t.installation_number;
            List<int> check = db.tasks_installation.Where(v => v.installation_number == tt).Select(p => p.task_number).ToList();           
            
            if (check.Count>0)
            {   //install exist

ck-project/ck-project/Controllers/ProductController.cs
using ck_project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ck_project.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        // GET: Product
        ckdatabase db = new ckdatabase();
        
        //main view
        public ActionResult View(int id,string msg=null) {
            List<string> pset = db.products.Where(a => a.lead_number == id && a.deleted==false).Select(e=> e.cat_anme).Distinct().ToList();
            var lead = db.leads.Where(l => l.lead_number == id).First();
            ViewBag.lid = id;
            ViewBag.customerNbr = lead.customer_number;

            List<Pg> agent = new List<Pg>();
            foreach (var a in pset) {
                agent.Add(new Pg { cat = a, lid = id ,uid=a.Split(' ')[0].Replace('/','_').Replace(',','C')});
            }

            return View(agent);
        }

        //create new
        public ActionResult Add(int lid) {
            ViewBag.lid = lid;
            List<SelectListItem> cat = new List<SelectListItem>();
            foreach (var a in Helpers.Constants.catDefList)
            {
                cat.Add(new SelectListItem { Text = a, Value = a });
            }
            ViewBag.catlist = cat;
            return PartialView();
        }

        [HttpPost]
        public ActionResult Add(FormCollection fo,int lid) {
            lead mian = db.leads.Where(a => a.lead_number == lid).FirstOrDefault();
            product target = new product();
            
            TryUpdateModel<product>(target, new string[] {"cat_anme","quantity","Description","model","color","product_source","manufacture","location","price" }, fo.ToValueProvider());
            //target.cat_anme = fo["Product Category"];
            if (ModelState.IsValid) {
                mian.products.Add(target);
                db.products.Add(target);
                db.SaveChanges(lid);
            }

            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);

        }

        ///**
        // * <param name="id"> id here means product id not lead id
        // * as lead id already in product</param>
        // * */
        //public ActionResult Edit(int id) {
        //    //todo: another listing
        //    return View();
        //}


        //[HttpPost]
        //public ActionResult Edit(FormCollection fo, int id) {

        //    return View(); 
        //}

        //helper
        public ActionResult gp(string cat,int lid) {
            List<product> ll = db.products.Where(a => a.lead_number == lid && a.cat_anme.Equals(cat) && a.deleted==false).ToList();
            List<SelectListItem> catt = new List<SelectListItem>();
            foreach (var a in Helpers.Constants.catDefList)
            {
                catt.Add(new SelectListItem { Text = a, Value = a });
            }
            ViewBag.catlist = catt;
            return PartialView(ll);
        }

        //[HttpPost]
        //public ActionResult gp(FormCollection fo) {
        //    int id = int.Parse(fo["item.product_number"]);
        //    product target = db.products.Where(a => a.product_number == id).FirstOrDefault();
        //    TryUpdateModel(target, new string[] { "quantity","Description","model","color", "product_source", "manufacture", "location", "price" },fo.ToValueProvider());
        //    if (ModelState.IsValid) {
        //        db.SaveChanges(id);
        //    }
        //    //ViewBag.lid = id;
        //    string cat = fo["item.cat_anme"];
        //    List<product> ll = db.products.Where(d => d.lead_number == target.lead_number && d.cat_anme.Equals(cat)).ToList();
        //        return PartialView(ll); 

        //    }

        //public ActionResult Notify(int id,string status) {
        //    ViewBag.lid = id;
        //    switch (status) {
        //        case "ok":
        //            ViewBag.outt= "change sussfuelly";
        //            break;
        //        case "bad":
        //            ViewBag.outt = "chage not sucessful";
        //            break;
        //        default:
        //            ViewBag.outt = "system error";
        //            break;

        //    }
        //    return View();
        //}

        //@model=product, not gp
        [HttpPost]
        public ActionResult handle(int pid,FormCollection fo) {
            product target = db.products.Where(a => a.product_number == pid).FirstOrDefault();
            int lid = target.lead_number;
            //not work?
            //TryUpdateModel(target, fo.ToValueProvider());
            target.color = fo["item.color"];
            target.Description = fo["item.Description"];
            target.location = fo["item.location"];
            target.manufacture = fo["item.manufacture"];
            target.model = fo["item.model"];
            target.price = Double.Parse(fo["item.price"]);
            target.product_source = fo["item.product_source"];
            target.quantity = int.Parse(fo["item.quantity"]);
            //target.cat_anme = fo["item.cat_anme"];
            if (ModelState.IsValid) {
                db.SaveChanges(lid);
                return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
            }

            //return RedirectToAction("view",new {id=target.lead_number });
            return null;
             
        }

        //delete
        public ActionResult DelP(int pid) {
            product target = db.products.Where(p => p.product_number == pid).First();
            int lid = target.lead_number;
            target.deleted = true;
            //db.products.Remove(target);
            db.SaveChanges(lid);

            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }
    }

}

ck-project/ck-project/Views/Product/Add.cshtml
@model ck_project.product

@{
    Layout = null;
}

<div>
@using (Html.BeginForm("Add","Product",new { lid=ViewBag.lid}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>All field with srart is required</h4>
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.cat_anme, "Category Name",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-xs-4">
               
                @Html.DropDownListFor(Model=>Model.cat_anme,(List<SelectListItem>)ViewBag.catlist, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cat_anme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantity, "* Quantity ",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-xs-4">
                @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, "Description",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-xs-4">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.model, "Model Name",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-xs-4">
                @Html.EditorFor(model => model.model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.color, "Color",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-xs-4">
                @Html.EditorFor(model => model.color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.product_source, "Vendor Source",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-xs-4">
                @Html.EditorFor(model => model.product_source, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.product_source, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.manufacture, "Manufacturer",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-xs-4">
                @Html.EditorFor(model => model.manufacture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.manufacture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.location, "Location",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-xs-4">
                @Html.EditorFor(model => model.location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, "* Price",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-xs-4">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.lead_number, "lead_number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-xs-4">
                @Html.DropDownList("lead_number", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.lead_number, "", new { @class = "text-danger" })
            </div>*@
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.lead_number)
        </div>
        
       

        <div class="form-group">
            <div class="col-md-offset-2 col-xs-4">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
    </div>

@*<div>
    <a href="javascript:void(0);" onclick="history.go(-1);">i am done</a>
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ck-project/ck-project/Views/Product/Notify.cshtml
@Html.Action("View",new { id=ViewBag.lid})

ck-project/ck-project/Views/Product/View.cshtml
@model List<ck_project.Models.Pg> 


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/jquery-3.2.1.min.js")
    @if (ViewBag.msg != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                toastr.success('@ViewBag.msg');
            });
        </script>
    }

    <script type="text/javascript">
        $(document).ready(function () {
            $(".navbar-nav li").removeClass("active");//this will remove the active class from
            //previously active menu item
            $('#lead').addClass('active');
        });
    </script>
}

@{
    <link href="~/Content/Tabs.css" rel="stylesheet" type="text/css" />

    if (HttpContext.Current.User.IsInRole("Administrator"))
    {
        @Html.Partial("_AdminMenu")
    }
    else
    {
        @Html.Partial("_MainMenu")
    }
}

<div class="container">
    <table>
        <tr>
            <td style="width:947px"><h2>Products</h2></td>
            <td style="width:50px">
                <input type="button" value="Customer" onclick="location.href='@Url.Action("Edit", "Customers", new { id = ViewBag.customerNbr })'" class="btn btn-default" id="tabBtn" />
            </td>
            <td style="width:50px">
                <input type="button" value="Lead" onclick="location.href='@Url.Action("Edit", "Lead", new { id = ViewBag.lid })'" class="btn btn-default" id="tabBtn" />
            </td>
            <td style="width:100px">
                <input type="button" value="Installation" onclick="location.href='@Url.Action("Lis", "Install", new { lid = ViewBag.lid })'" class="btn btn-default" id="tabBtn" />
            </td>
            <td style="width:50px">
                <input type="button" value="Summary" onclick="location.href='@Url.Action("ProjSummary", "Home", new { id = ViewBag.lid })'" class="btn btn-default" id="tabBtn" />
            </td>
            <td style="width:50px">
                <input type="button" value="Print" onclick="location.href='@Url.Action("ProjPrint", "Home", new { id = ViewBag.lid })'" class="btn btn-default" id="tabBtn" />
            </td>
        </tr>
    </table>
    <hr />

    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <h3 class="panel-heading">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapseR" style="color:#8B0000">
                    Add New Product
                </a>
            </h3>

            <div id="collapseR" class="panel-collapse collapse">
                <div class="panel-body">
                    @{
                        if (Model != null)
                        {
                            @Html.Action("Add", new { lid = ViewBag.lid })
                        }
                    }
                </div>
            </div>
        </div>

        @foreach (var item in Model)
        {
            var cat = item.cat;
            var lid = item.lid;

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion"
                           href="#collapse@(item.uid)">
                            @item.cat
                        </a>

                    </h4>
                </div>
                <div id="collapse@(item.uid)" class="panel-collapse collapse">
                    <div class="panel-body">


                        @Html.Action("gp", new { cat = cat, lid = lid })
                    </div>
                </div>
            </div>

        }
    </div>
</div>

ck-project/ck-project/Views/Product/gp.cshtml
@model IEnumerable<ck_project.product>

@{
    Layout = null;
}

@foreach (var item in Model)
{
    using (Html.BeginForm("handle","Product",new {pid=item.product_number }))
    {
    @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>@item.Description</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => item.product_number)

            @*<div class='col-xs-4 '>
                <div class="form-group">
                    <label class="control-label" for="name">Category*</label>
                    @Html.DropDownListFor(Model=>item.cat_anme, (List<SelectListItem>)ViewBag.catlist, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => item.cat_anme, "", new { @class = "text-danger" })
                </div>
            </div>*@
            <div class='col-xs-4 '>
                <div class="form-group">
                    <label class="control-label" for="name">Quantity*</label>
                    @Html.EditorFor(model => item.quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => item.quantity, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class='col-xs-4 '>
                <div class="form-group">
                    <label class="control-label" for="name">Description*</label>
                    @Html.EditorFor(model => item.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => item.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class='col-xs-4 '>
                <div class="form-group">
                    <label class="control-label" for="name">Model</label>
                    @Html.EditorFor(model => item.model, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => item.model, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class='col-xs-4 '>
                <div class="form-group">
                    <label class="control-label" for="name">Color</label>
                    @Html.EditorFor(model => item.color, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => item.color, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class='col-xs-4 '>
                <div class="form-group">
                    <label class="control-label" for="name">Vendor Source</label>
                    @Html.EditorFor(model => item.product_source, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => item.product_source, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class='col-xs-4 '>
                <div class="form-group">
                    <label class="control-label" for="name">Manufacturer</label>
                    @Html.EditorFor(model => item.manufacture, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => item.manufacture, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class='col-xs-4 '>
                <div class="form-group">
                    <label class="control-label" for="name">Location</label>
                    @Html.EditorFor(model => item.location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => item.location, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class='col-xs-4 '>
                <div class="form-group">
                    <label class="control-label" for="name">Price*</label>
                    @Html.EditorFor(model => item.price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => item.price, "", new { @class = "text-danger" })
                </div>
            </div>   


            <div class="form-group">
                <div class="col-xs-4">
                    @Html.ActionLink("Delete", "DelP", "Product", new { pid = item.product_number }, new { @class = "btn btn-default" })
                </div>
                <div class="col-xs-4 col-xs-offset-4">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>

            </div>
        </div>
    }
 }



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}